public class Main {
    public static void main(String[] args) {
        int a;
        a = 27897;
        byte b;
        b = 67;
        short c;
        c = 569;
        long d;
        d = 987678965549L;
        float g;
        g = 2.786F;
        double q;
        q = 27.12;
        short w;
        w = -159;
        System.out.println("значение переменной 'a' с типом int равно " + a);
        System.out.println(" значение переменной 'b' с типом byte равно " + b);
        System.out.println(" значение переменной 'c' с типом short равно " + c);
        System.out.println(" значение переменной 'd' с типом long равно " + d);
        System.out.println(" значение переменной 'g' с типом float равно " + g);
        System.out.println(" значение переменной 'q' с типом double равно " + q);
        System.out.println(" значение переменной 'w' с типом short равно " + w);
        byte Luda;
        Luda = 23;
        byte Anna;
        Anna = 27;
        byte Katy;
        Katy = 30;
        int result;
        result = 480 / (Luda + Anna + Katy);
        System.out.println("На каждого ученика расчитано " + result + " листов бумаги");
        byte bottle;
        bottle = 16 / 2;
        System.out.println("За 1 минуту машина произвела " + bottle + " штук бутылок");
        short bottle2;
        bottle2 = 8 * 20;
        System.out.println(" За 20 минут машина произвела " + bottle2 + " штук бутылок");
        short bottle3;
        bottle3 = 8 * 60 * 24;
        System.out.println(" За сутки машина произвела " + bottle3 + " штук бутылок");
        int bottle4;
        bottle4 = 8*60*24*3;
        System.out.println(" За 3 дня машина произвела " + bottle4 + " штук бутылок");
        int bottle5;
        bottle5 = 8*60*24*30;
        System.out.println(" За месяц машина произвела " + bottle5 + " штук бутылок");
        byte school;
        school = 120 / (2 + 4);
        byte colorW;
        colorW = 20 * 2;
        byte colorG;
        colorG = 20 * 4;
        System.out.println("В школе, где " + school + " классов, нужно " + colorW + " банок белой краски и " + colorG + " банок коричневой краски");
        int banana;
        banana = 5 * 80;
        int milk;
        milk = (200 / 100) * 105;
        int ice;
        ice = 2 * 100;
        int eggs;
        eggs = 4 * 70;
        int result2;
        result2 = banana + milk + ice + eggs;
        int result3;
        result3 = result2 / 1000;
        System.out.println(" вес такого спортзавтрака " + result2 + " граммов ");
        System.out.println(" вес такого спортзавтрака " + result3 + " килограмм ");
    }
}